<?php

namespace Thruway\SwooleTransport;

use Thruway\SwooleTransport\Connection\ConnectionInterface;
use React\EventLoop\LoopInterface;
use Thruway\Exception\PingNotSupportedException;
use Thruway\Message\Message;
use Thruway\Transport\AbstractTransport;

class SwooleTransport extends AbstractTransport
{
    private int $pingSeq;

    private array $pingRequests;

    public function __construct(private ConnectionInterface $connection, LoopInterface $loop)
    {
        $this->pingSeq = 1234;
        $this->pingRequests = [];

        $this->loop = $loop;
    }

    public function getTransportDetails(): array
    {
        return [
            'type' => 'openswoole',
            'headers' => $this->connection->getRequest()->header,
            'server' => $this->connection->getRequest()->server,
        ];
    }

    public function sendMessage(Message $msg): void
    {
        $this->connection->send($this->getSerializer()->serialize($msg));
    }

    public function close(): void
    {
        $this->connection->close();
    }

    /**
     * @throws PingNotSupportedException
     */
    public function ping(): void
    {
        parent::ping(); // TODO: Change the autogenerated stub
    }
}